export const vehicleInfotainmentSystemItemsToSeize = [
	'Live and deleted user attribution data including user accounts, e-mail accounts, passwords, PIN codes, patterns, methods of payment, account names, user names, screen names, remote data storage accounts, documents, files, metadata, log files, user voice profiles and other biometric identifiers or any other information and evidence that may demonstrate attribution to a particular user or users',
	'Live and deleted historical navigation data tracks, routes, and waypoints, GPS fixes, favorites, past journeys, trip logs, and user entered data, Latitude, Longitude, and Altitude coordinates, and related dates and times pertaining to Subject Offense(s)',
	'Live and deleted logs, records, documents, and other items that may constitute evidence, contraband, fruits, and/or instrumentalities of violations of crimes, pertaining to Subject Offense(s)',
	'Live and deleted contact lists, call logs, text messages and multimedia messages (SMS and MMS messages), e-mails, chats, video conference communication data, contact information, installed application information including their content and any other information which can be used to identify potentially associated persons pertaining to Subject Offense(s)',
	'Live and deleted passwords, password files, PIN codes, encryption codes, or other information necessary to access the digital device or data stored on the digital device such as hidden file applications',
	'Live and deleted documents, programs, pictures, videos, audio files, text files, databases, application data, calendar entries, user dictionaries, malware, viruses, tracking or other remote monitoring software, and any associated metadata pertaining to Subject Offense(s)',
	'Live and deleted web browser history, web browser bookmarks, temporary Internet files, cookies, searched items, downloaded and uploaded files, social networking websites or applications pertaining to Subject Offense(s)',
	'Live and deleted data stored on removable media such as Subscriber Identity Modules (SIM cards), flash memory storage devices such as Secure Digital (SD) and Micro SD media cards and any associated wireless devices (Bluetooth, Wi-Fi, or other technology) pertaining to Subject Offense(s)',
	'Live and deleted historical event data to include, but not limited to, when the headlights were on or off, when doors were opened or closed, when gears were changed, when brakes were applied, and when connections and disconnections were made to other devices, such as Bluetooth, media cards and Wi-Fi pertaining to Subject Offense(s)'
];
